# Generated by Django 6.0.5 on 2026-05-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=100)),
                ('contrasenha', models.CharField(db_column='contrasenha', max_length=30)),
                ('estado_cuenta', models.CharField(db_column='estado_cuenta', max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorProceso',
            fields=[
                ('id_error', models.IntegerField(db_column='id_error', primary_key=True, serialize=False)),
                ('modulo_origen', models.CharField(db_column='modulo_origen', max_length=100)),
                ('procedimiento_origen', models.CharField(db_column='procedimiento_origen', max_length=100)),
                ('mensaje_error', models.CharField(db_column='mensaje_error', max_length=255)),
                ('fecha_error', models.DateField(db_column='fecha_error')),
                ('id_usuario', models.IntegerField(db_column='id_usuario')),
                ('id_carga', models.IntegerField(db_column='id_carga')),
                ('id_registro_llamada', models.IntegerField(db_column='id_registro_llamada')),
                ('detalle_error', models.CharField(db_column='detalle_error', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLlamada',
            fields=[
                ('id_tipo_llamada', models.IntegerField(db_column='id_tipo_llamada', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.IntegerField(db_column='id_tipo_reporte', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id_registro_llamada', models.IntegerField(db_column='id_registro_llamada', primary_key=True, serialize=False)),
                ('id_carga', models.IntegerField(db_column='id_carga')),
                ('anexo', models.CharField(db_column='anexo', max_length=100)),
                ('numero_destino', models.IntegerField(db_column='numero_destino', max_length=10)),
                ('duracion_segundos', models.IntegerField(db_column='duracion_segundos', max_length=255)),
                ('proveedor', models.CharField(db_column='proveedor', max_length=100)),
                ('fecha_llamada', models.DateField(db_column='fecha_llamada')),
                ('fecha_proceso', models.DateField(db_column='fecha_proceso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.usuario')),
                ('id_tipo_llamada', models.ForeignKey(db_column='id_tipo_llamada', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.tipollamada')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteTarificacion',
            fields=[
                ('id_reporte_tarificacion', models.IntegerField(db_column='id_reporte_tarificacion', primary_key=True, serialize=False)),
                ('id_carga', models.IntegerField(db_column='id_carga')),
                ('anexo', models.CharField(db_column='anexo', max_length=100)),
                ('duracion_total_segundos', models.IntegerField(db_column='duracion_total_segundos', max_length=255)),
                ('proveedor', models.CharField(db_column='proveedor', max_length=100)),
                ('cant_llamadas_usuario', models.IntegerField(db_column='cant_llamadas_usuario', max_length=10)),
                ('cant_total_llamadas_usuario', models.IntegerField(db_column='cant_total_llamadas_usuario', max_length=10)),
                ('total_tiempo_carga', models.IntegerField(db_column='total_tiempo_carga', max_length=10)),
                ('prom_duracion_llamada', models.IntegerField(db_column='prom_duracion_llamada', max_length=10)),
                ('costo_calculado', models.IntegerField(db_column='costo_calculado', max_length=10)),
                ('fecha_proceso', models.DateField(db_column='fecha_proceso')),
                ('id_registro_llamada', models.ForeignKey(db_column='id_registro_llamada', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.registrollamada')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.usuario')),
                ('id_tipo_llamada', models.ForeignKey(db_column='id_tipo_llamada', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.tipollamada')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReporte',
            fields=[
                ('id_solicitud', models.IntegerField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('id_carga', models.IntegerField(db_column='id_carga')),
                ('fecha_solicitud', models.DateField(db_column='fecha_solicitud')),
                ('estado_solicitado', models.CharField(db_column='estado_solicitado', max_length=20)),
                ('ruta_reporte', models.CharField(db_column='ruta_reporte', max_length=100)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.usuario')),
                ('id_tipo_reporte', models.ForeignKey(db_column='id_tipo_reporte', on_delete=django.db.models.deletion.DO_NOTHING, to='procesamiento.tiporeporte')),
            ],
        ),
    ]
