# Generated by Django 6.0.5 on 2026-05-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorproceso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registrollamada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reportetarificacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solicitudreporte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipollamada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tiporeporte',
            options={'managed': False},
        ),
    ]
