# Generated by Django 6.0.5 on 2026-05-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_alter_errorproceso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='errorproceso',
            table='error_proceso',
        ),
        migrations.AlterModelTable(
            name='registrollamada',
            table='registro_llamada',
        ),
        migrations.AlterModelTable(
            name='reportetarificacion',
            table='reporte_tarificacion',
        ),
        migrations.AlterModelTable(
            name='solicitudreporte',
            table='solicitud_reporte',
        ),
        migrations.AlterModelTable(
            name='tipollamada',
            table='tipo_llamada',
        ),
        migrations.AlterModelTable(
            name='tiporeporte',
            table='tipo_reporte',
        ),
    ]
