# Generated by Django 6.0.5 on 2026-05-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0003_alter_errorproceso_table_alter_registrollamada_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='errorproceso',
            table='ERROR_PROCESO',
        ),
        migrations.AlterModelTable(
            name='registrollamada',
            table='REGISTRO_LLAMADA',
        ),
        migrations.AlterModelTable(
            name='reportetarificacion',
            table='REPORTE_TARIFICACION',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='ROL',
        ),
        migrations.AlterModelTable(
            name='solicitudreporte',
            table='SOLICITUD_REPORTE',
        ),
        migrations.AlterModelTable(
            name='tipollamada',
            table='TIPO_LLAMADA',
        ),
        migrations.AlterModelTable(
            name='tiporeporte',
            table='TIPO_REPORTE',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
    ]
